[project]
name = "software_development_tool_project"
version = "0.0.1"

dependencies = [
    "pandas",
    "streamlit",
    "plotly.express",
    "altair",
    "jupyter",
    "plotly-express",
    "matplotlib",
    "numpy"
    
]
